### ISSUE TITLE
failed to download fast ycb dataset

### ISSUE THREAD

**Issue by huangyi16** [robotology/optical-flow-6d-tracking-code#5]
the following error appears when i run the script "download_fastycb.sh":
**curl: (6) Could not resolve host: storage-dataverse.iit.it**

It seems that I don't have the right to access this website. How should I solve this problem?
thanks.

**Comment by xEnVrE** [comment]
Dear @huangyi16, 

Thanks for showing interest in our work.

Unfortunately it seems that our internal server stopped working. It does not depend on any kind of permission from your side.

Sorry for the inconvenience.

I will contact our IT department and let you know as soon as possible.

**Comment by huangyi16** [comment]
Okay. I see. Thanks very much.

**Comment by xEnVrE** [comment]
Dear @huangyi16,

our IT department is aware of the problem and they are working to find the solution.

I keep you posted.

Thank you

**Comment by xEnVrE** [comment]
Dear @huangyi16,

the issue should have been solved by now. Can you retry and let us know if you can download the dataset successfully?

Thank you

**Comment by huangyi16** [comment]
Yes, the dataset can be downloaded now.
Thanks for your kindly help! @xEnVrE

**Comment by xEnVrE** [comment]
You are welcome @huangyi16 !
